// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/internal/review-queue": {
            "post": {
                "description": "Laravel internal endpoint used by the Go review outbox. ` + "`" + `X-AI-Signature` + "`" + ` is lowercase hex HMAC-SHA256 over ` + "`" + `\u003ctimestamp\u003e.\u003craw JSON body\u003e` + "`" + ` using ` + "`" + `GO_AI_WEBHOOK_SECRET` + "`" + `.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "laravel-callbacks"
                ],
                "summary": "Receive signed Laravel review queue callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unix seconds timestamp, accepted within GO_AI_WEBHOOK_TOLERANCE",
                        "name": "X-AI-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Lowercase hex HMAC-SHA256 of '\u003ctimestamp\u003e.\u003craw body\u003e'",
                        "name": "X-AI-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Review queue callback",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.reviewQueueCallbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Existing idempotent review item",
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.reviewQueueCallbackResponse"
                        }
                    },
                    "201": {
                        "description": "Created review queue item",
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.reviewQueueCallbackResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/admin/review-queue/{id}/approve": {
            "post": {
                "description": "Promotes the review queue item into its target (symptom node, subject, or KB article).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review-queue"
                ],
                "summary": "Approve review queue item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Review item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.reviewApproveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/admin/review-queue/{id}/reject": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "review-queue"
                ],
                "summary": "Reject review queue item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Review item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review rejection",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.reviewRejectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/chat": {
            "post": {
                "description": "Runs the tenant-scoped chat workflow. Set debug=true to include stage_timings_ms for fast_guard, router, cache, knowledge, render, resolve, generate, parse, and store_cache.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Create chat turn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request budget in milliseconds; Go runs within this minus headroom, falling back to server config when absent",
                        "name": "X-Timeout-Ms",
                        "in": "header"
                    },
                    {
                        "description": "Chat request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/chat/confirm-action": {
            "post": {
                "description": "Executes an action previously proposed via ` + "`" + `pending_action` + "`" + ` in a /v1/chat or /v1/chat/stream response. ` + "`" + `action_id` + "`" + ` is the 32-character id from that field.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Confirm a pending chat action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Confirm request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/chat/stream": {
            "post": {
                "description": "Server-Sent Events variant of /v1/chat. Each frame is ` + "`" + `event: \u003ctype\u003e\\ndata: \u003cjson\u003e` + "`" + `; types are start, token, tool, pending_action, done, error. Same request body and stage set as /v1/chat.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Create chat turn (streaming)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request budget in milliseconds; Go runs within this minus headroom, falling back to server config when absent",
                        "name": "X-Timeout-Ms",
                        "in": "header"
                    },
                    {
                        "description": "Chat request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatStreamEvent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/inbound/email": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbound"
                ],
                "summary": "Receive email inbound webhook",
                "parameters": [
                    {
                        "description": "Email webhook payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.emailInboundWebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/inbound/line": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbound"
                ],
                "summary": "Receive LINE inbound webhook",
                "parameters": [
                    {
                        "description": "LINE webhook payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.lineInboundWebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/reply": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reply"
                ],
                "summary": "Create reply",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request budget in milliseconds; Go runs within this minus headroom, falling back to server config when absent",
                        "name": "X-Timeout-Ms",
                        "in": "header"
                    },
                    {
                        "description": "Reply request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.ReplyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.ReplyResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/reply/feedback": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reply"
                ],
                "summary": "Record reply feedback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Smart-reply feedback",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.feedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/reports/ai-accuracy": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "AI accuracy report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 timestamp, or an integer number of days ago",
                        "name": "since",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.aiAccuracyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/reports/answer-rate": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Answer rate report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 timestamp, or an integer number of days ago",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Confidence threshold, default 0.85",
                        "name": "threshold",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.answerRateResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/reports/knowledge-gaps": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Knowledge gaps report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max rows, default 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scripts_swagger.knowledgeGapsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        },
        "/v1/search": {
            "post": {
                "description": "Embeds the query, runs ANN search over the tenant's vector collection, and resolves hits back to reports. When types includes \"kb\" and Memgraph is enabled, each hit's classification symptom is used as a graph anchor to pull related knowledge articles. graph_anchors reports how many distinct symptoms were resolved: zero means the tenant has no classification rows, so the graph leg cannot return anything.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Semantic search over reports and knowledge articles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cRS256 service JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "X-Tenant-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request budget in milliseconds; Go runs within this minus headroom, falling back to server config when absent",
                        "name": "X-Timeout-Ms",
                        "in": "header"
                    },
                    {
                        "description": "Search request; types defaults to [report, kb], limit 1-50",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_my_app_internal_application_dto.SearchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Envelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_my_app_internal_application_dto.AttachmentRef": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer",
                    "minimum": 0
                },
                "storage_key": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatActivity": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatCaseDraft": {
            "type": "object",
            "properties": {
                "contact": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "problem": {
                    "type": "string"
                },
                "product": {
                    "type": "string"
                },
                "ready": {
                    "type": "boolean"
                },
                "severity": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatCaseResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatConfirmRequest": {
            "type": "object",
            "properties": {
                "action_id": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatDebug": {
            "type": "object",
            "properties": {
                "cache_hit": {
                    "type": "boolean"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatDebugEvent"
                    }
                },
                "stage_timings_ms": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "tool": {
                    "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatToolDebug"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatDebugEvent": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "duration_ms": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatMessage": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.AttachmentRef"
                    }
                },
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatPendingAction": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "summary": {
                    "type": "string"
                },
                "tool_id": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatRequest": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "integer"
                },
                "debug": {
                    "type": "boolean"
                },
                "locale": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatMessage"
                    }
                },
                "mode": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatResponse": {
            "type": "object",
            "properties": {
                "activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatActivity"
                    }
                },
                "case": {
                    "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatCaseDraft"
                },
                "conversation_id": {
                    "type": "integer"
                },
                "debug": {
                    "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatDebug"
                },
                "model": {
                    "type": "string"
                },
                "pending_action": {
                    "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatPendingAction"
                },
                "reply": {
                    "type": "string"
                },
                "search_results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatCaseResult"
                    }
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatSource"
                    }
                },
                "stage_timings_ms": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "status": {
                    "type": "string"
                },
                "tool_result": {
                    "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatToolResult"
                },
                "transcript": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatSource": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "snippet": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatStreamEvent": {
            "type": "object",
            "properties": {
                "activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatActivity"
                    }
                },
                "code": {
                    "type": "string"
                },
                "debug": {
                    "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatDebug"
                },
                "message": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "pending_action": {
                    "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatPendingAction"
                },
                "search_results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatCaseResult"
                    }
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatSource"
                    }
                },
                "status": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "tool_result": {
                    "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatToolResult"
                },
                "transcript": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatToolColumn": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "primary": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatToolDebug": {
            "type": "object",
            "properties": {
                "called": {
                    "type": "boolean"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "handler": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "matched": {
                    "type": "boolean"
                },
                "mutates": {
                    "type": "boolean"
                },
                "outcome": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "permission_filtered": {
                    "type": "boolean"
                },
                "required_permission": {
                    "type": "string"
                },
                "retrieval_score": {
                    "type": "number"
                },
                "router_confidence": {
                    "type": "number"
                },
                "router_intent": {
                    "type": "string"
                },
                "row_count": {
                    "type": "integer"
                },
                "selection_score": {
                    "type": "number"
                },
                "tool_id": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ChatToolResult": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ChatToolColumn"
                    }
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                },
                "tool_id": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ReplyRequest": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.AttachmentRef"
                    }
                },
                "channel": {
                    "type": "string",
                    "enum": [
                        "line",
                        "email",
                        "web",
                        "voice",
                        "api",
                        "in_app"
                    ],
                    "example": "web"
                },
                "conversation_id": {
                    "type": "string",
                    "example": "conv_8f21"
                },
                "customer_id": {
                    "type": "string",
                    "example": "cust_10293"
                },
                "debug": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "My internet has been offline since this morning."
                },
                "message_id": {
                    "type": "string",
                    "example": "msg_1001"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "mode": {
                    "type": "string",
                    "enum": [
                        "fast_draft",
                        "full_review",
                        "debug"
                    ],
                    "example": "full_review"
                },
                "query": {
                    "type": "string"
                },
                "site_id": {
                    "type": "string",
                    "example": "site_42"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ReplyResponse": {
            "type": "object",
            "properties": {
                "ai_action_id": {
                    "type": "integer"
                },
                "confidence": {
                    "type": "number"
                },
                "debug_trace": {},
                "decision": {
                    "type": "string"
                },
                "draft": {
                    "type": "string"
                },
                "intent": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "retry_after_ms": {
                    "type": "integer"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.ReplySource"
                    }
                },
                "stage_timings_ms": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "suggestion": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.ReplySource": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_application_dto.SearchRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_my_app_internal_application_dto.SearchResponse": {
            "type": "object",
            "properties": {
                "graph_anchors": {
                    "type": "integer"
                },
                "graph_used": {
                    "type": "boolean"
                },
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_my_app_internal_application_dto.SearchResult"
                    }
                },
                "vector_hits": {
                    "type": "integer"
                }
            }
        },
        "github_com_my_app_internal_application_dto.SearchResult": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "report_id": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_my_app_internal_transport_http_response.Envelope": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_my_app_internal_transport_http_response.Error"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_my_app_internal_transport_http_response.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "scripts_swagger.aiAccuracyData": {
            "type": "object",
            "properties": {
                "human_confirmed": {
                    "type": "integer",
                    "example": 98
                },
                "problem_type_hits": {
                    "type": "integer",
                    "example": 90
                },
                "severity_hits": {
                    "type": "integer",
                    "example": 88
                },
                "subject_hits": {
                    "type": "integer",
                    "example": 95
                },
                "symptom_hits": {
                    "type": "integer",
                    "example": 80
                },
                "total_classified": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "scripts_swagger.aiAccuracyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/scripts_swagger.aiAccuracyData"
                }
            }
        },
        "scripts_swagger.answerRateData": {
            "type": "object",
            "properties": {
                "high_confidence": {
                    "type": "integer",
                    "example": 170
                },
                "latency_avg_ms": {
                    "type": "integer",
                    "example": 850
                },
                "threshold": {
                    "type": "number",
                    "example": 0.85
                },
                "total_actions": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "scripts_swagger.answerRateResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/scripts_swagger.answerRateData"
                }
            }
        },
        "scripts_swagger.emailInboundWebhookRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "The connection has been unstable since this morning."
                },
                "body_html": {
                    "type": "string",
                    "example": "\u003cp\u003eThe connection has been unstable since this morning.\u003c/p\u003e"
                },
                "from": {
                    "type": "string",
                    "example": "Customer One \u003ccustomer@example.com\u003e"
                },
                "message_id": {
                    "type": "string",
                    "example": "email-20260520-001"
                },
                "subject": {
                    "type": "string",
                    "example": "Internet connection issue"
                },
                "to": {
                    "type": "string",
                    "example": "support@example.com"
                }
            }
        },
        "scripts_swagger.feedbackRequest": {
            "type": "object",
            "properties": {
                "ai_action_id": {
                    "type": "integer",
                    "example": 42
                },
                "note": {
                    "type": "string",
                    "example": "Agent sent the draft unchanged."
                },
                "verdict": {
                    "type": "string",
                    "enum": [
                        "accepted",
                        "edited",
                        "rejected",
                        "escalated"
                    ],
                    "example": "accepted"
                }
            }
        },
        "scripts_swagger.knowledgeGapRow": {
            "type": "object",
            "properties": {
                "first_seen": {
                    "type": "string",
                    "example": "2026-07-01T09:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 7
                },
                "last_seen": {
                    "type": "string",
                    "example": "2026-08-01T09:00:00Z"
                },
                "occurrence_count": {
                    "type": "integer",
                    "example": 14
                },
                "query_text": {
                    "type": "string",
                    "example": "how to reset password"
                },
                "status": {
                    "type": "string",
                    "example": "open"
                }
            }
        },
        "scripts_swagger.knowledgeGapsData": {
            "type": "object",
            "properties": {
                "gaps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripts_swagger.knowledgeGapRow"
                    }
                }
            }
        },
        "scripts_swagger.knowledgeGapsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/scripts_swagger.knowledgeGapsData"
                }
            }
        },
        "scripts_swagger.lineInboundEvent": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/scripts_swagger.lineInboundMessage"
                },
                "replyToken": {
                    "type": "string",
                    "example": "reply-token-example"
                },
                "source": {
                    "$ref": "#/definitions/scripts_swagger.lineInboundSource"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1716172800000
                },
                "type": {
                    "type": "string",
                    "example": "message"
                }
            }
        },
        "scripts_swagger.lineInboundMessage": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "519551372899"
                },
                "text": {
                    "type": "string",
                    "example": "My internet is offline"
                },
                "type": {
                    "type": "string",
                    "example": "text"
                }
            }
        },
        "scripts_swagger.lineInboundSource": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "string",
                    "example": "C4af4980629"
                },
                "roomId": {
                    "type": "string",
                    "example": "R4af4980629"
                },
                "type": {
                    "type": "string",
                    "example": "user"
                },
                "userId": {
                    "type": "string",
                    "example": "U4af4980629"
                }
            }
        },
        "scripts_swagger.lineInboundWebhookRequest": {
            "type": "object",
            "properties": {
                "destination": {
                    "type": "string",
                    "example": "U1234567890abcdef1234567890abcdef"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripts_swagger.lineInboundEvent"
                    }
                }
            }
        },
        "scripts_swagger.reviewApproveData": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string",
                    "example": "symptom_proposed"
                },
                "promotion_ref": {
                    "type": "string",
                    "example": "symptom_node:456"
                },
                "review_item_id": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "scripts_swagger.reviewApproveResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/scripts_swagger.reviewApproveData"
                }
            }
        },
        "scripts_swagger.reviewQueueCallbackData": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "kind": {
                    "type": "string",
                    "example": "symptom_proposed"
                }
            }
        },
        "scripts_swagger.reviewQueueCallbackRequest": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer",
                    "example": 1
                },
                "kind": {
                    "type": "string",
                    "enum": [
                        "kb_promotion",
                        "symptom_proposed",
                        "subject_proposed",
                        "kb_gap"
                    ],
                    "example": "symptom_proposed"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": true
                },
                "payload_hash": {
                    "type": "string",
                    "example": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                },
                "source_refs": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "scripts_swagger.reviewQueueCallbackResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/scripts_swagger.reviewQueueCallbackData"
                }
            }
        },
        "scripts_swagger.reviewRejectRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "The generated article duplicated an existing answer."
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Centric RAG AI Service",
	Description:      "Internal AI service for tenancy-scoped support retrieval and reply workflows.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
