package config

import "github.com/spf13/viper"

func setDefaults(v *viper.Viper) {
	v.SetDefault("app.env", "development")
	v.SetDefault("server.port", "8080")
	v.SetDefault("server.request_budget_ms", 22000)
	v.SetDefault("server.deadline_headroom_ms", 2000)
	v.SetDefault("server.deadline_min_ms", 1000)
	v.SetDefault("server.deadline_max_ms", 60000)

	v.SetDefault("intake.assess_mode", "inline")
	v.SetDefault("intake.assess_timeout_ms", 30000)
	v.SetDefault("mysql.enabled", false)
	v.SetDefault("mysql.maxOpenConns", 25)
	v.SetDefault("mysql.maxIdleConns", 5)
	v.SetDefault("qdrant.enabled", false)
	v.SetDefault("qdrant.url", "http://localhost:6333")
	v.SetDefault("qdrant.collectionPrefix", "kb_chunks")
	v.SetDefault("memgraph.enabled", false)
	v.SetDefault("memgraph.uri", "bolt://localhost:7687")
	v.SetDefault("llm.enabled", true)
	v.SetDefault("llm.default_vendor", "gemini")
	v.SetDefault("llm.default_model", "gemini-2.5-flash")
	v.SetDefault("llm.request_timeout_seconds", 8)
	v.SetDefault("llm.breaker_failures", 5)
	v.SetDefault("llm.breaker_cooldown_seconds", 30)
	v.SetDefault("llm.max_retries", 1)
	v.SetDefault("llm.retry_base_backoff_ms", 400)
	v.SetDefault("llm.retry_max_backoff_ms", 1500)
	v.SetDefault("llm.rate_limit_per_sec", 0)
	v.SetDefault("llm.rate_limit_burst", 0)
	v.SetDefault("llm.resolver_cache_ttl_seconds", 60)
	v.SetDefault("logger.level", "info")
	v.SetDefault("logger.format", "console")
	v.SetDefault("swagger.enabled", true)
	v.SetDefault("budget.maxLLMCallsPerRequest", 6)
	v.SetDefault("budget.maxLLMCallsPerCompanyWindow", 0)
	v.SetDefault("budget.windowSeconds", 60)
	v.SetDefault("chat.cacheTTLSeconds", 300)
	v.SetDefault("chat.cacheMaxEntries", 4096)
	v.SetDefault("embedding.refreshMaxChunks", 512)
	v.SetDefault("embedding.refreshBatchSize", 64)
	v.SetDefault("embedding.largeRunThreshold", 1000)
	v.SetDefault("reply.defaultMode", "full")
	v.SetDefault("entitlements.cache_ttl_seconds", 60)
}
